# Traffic Route Optimization System
## Continous Evaluatoin - 1
This notebook contains the data preperation , preprocessing,
exploratory data analysis, feature engineering, and feature 
selection performed for the Traffic Route Optimization System.

The final objective of this stage is to prepare a clean, 
transformed, and analysed dataset ready for machine learning
model development.

## 1. Import Required Libraries

In [8]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn
print("All Libraries loaded Succefully")

All Libraries loaded Succefully

## 2. Problem Statement

In real-world transportation systems, selecting an efficient route can be affected by several factors such as traffic conditions, distance, travel-related conditions, and other environmental or road factors.

A route that is shortest in distance may not always be the quickest or most efficient route when traffic and other conditions are considered.

The objective of this project is to analyse relevant traffic and route data and develop a machine learning based approach that can assist in identifying an efficient route between a source and destination.

## 3. Project Objectives

1. Collect and understand a suitable dataset related to traffic and route conditions.

2. Clean and preprocess the dataset by handling duplicates, inconsistent data, missing values, and irrelevant information.

3. Perform exploratory data analysis and visualization to identify important patterns and relationships in the data.

4. Perform feature engineering and feature selection to identify relevant inputs for machine learning.

5. Prepare a clean and transformed dataset that is ready for subsequent machine learning model development.

## 4. Dataset Collection & Description

The dataset used for this project is the AetherGrid Smart Mobility Dataset. It contains mobility and traffic-related information for individual trips.

The dataset includes geographical information about the starting and ending locations of trips, trip distance, vehicle speed, traffic conditions, weather conditions, vehicle type, and temporal information.

The dataset is stored in CSV format and contains 50,000 records with 14 features. It will be used for data cleaning, exploratory data analysis, feature engineering, and preparation for subsequent machine learning model development.

In [9]:
import pandas as pd

# Path to the raw dataset
file_path = "../data/raw/AetherGrid_Mobility_Patterns_v2_Alpha9.csv"

# Load the dataset
df = pd.read_csv(file_path)

# Display the first five rows
df.head()

,user_id,trip_id,start_lat,start_lon,end_lat,end_lon,distance_km,speed_kmh,traffic,weather,vehicle_type,timestamp,day_of_week,is_weekend
0,U100,T9000,24.6970,67.4195,24.5436,67.7147,28.97,31.498106,Low,Clear,Bus,2025-01-24 12:20:00,4,0
1,U101,T9001,24.7596,67.0422,24.3896,67.3007,8.18,49.894966,Medium,Clear,Bus,2025-01-19 11:56:00,6,1
2,U102,T9002,24.1323,67.0737,23.7858,66.9700,13.45,34.706390,High,Clear,Bus,2025-01-28 10:51:00,1,0
3,U103,T9003,24.2530,67.8358,24.6431,68.0697,21.47,26.375888,High,Clear,Car,2025-01-29 08:53:00,2,0
4,U104,T9004,24.1442,66.7141,24.4542,66.3060,15.73,22.592173,High,Fog,Bike,2025-01-13 17:30:00,0,0

In [10]:
print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Dataset Shape: (50000, 14)

Column Names:
['user_id', 'trip_id', 'start_lat', 'start_lon', 'end_lat', 'end_lon', 'distance_km', 'speed_kmh', 'traffic', 'weather', 'vehicle_type', 'timestamp', 'day_of_week', 'is_weekend']

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       50000 non-null  str
 1   trip_id       50000 non-null  str
 2   start_lat     50000 non-null  float64
 3   start_lon     50000 non-null  float64
 4   end_lat       50000 non-null  float64
 5   end_lon       50000 non-null  float64
 6   distance_km   50000 non-null  float64
 7   speed_kmh     50000 non-null  float64
 8   traffic       50000 non-null  str
 9   weather       50000 non-null  str
 10  vehicle_type  50000 non-null  str
 11  timestamp     50000 non-null  str
 12  day_of_week   50000 non-null  int64
 13  is_weekend    50000 non-null  int64
dtypes: float64(6), int64(2), str(6)
memory usage: 5.3 MB

In [11]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
user_id,50000,50000,U100,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
trip_id,50000,50000,T9000,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
start_lat,50000.0,NaN,NaN,NaN,24.744345,0.435402,24.0,24.363575,24.7441,25.122325,25.5
start_lon,50000.0,NaN,NaN,NaN,67.253005,0.432677,66.5001,66.8785,67.2547,67.6273,68.0
end_lat,50000.0,NaN,NaN,NaN,24.743686,0.522188,23.5038,24.357275,24.7426,25.1288,25.9948
end_lon,50000.0,NaN,NaN,NaN,67.251135,0.520328,66.004,66.8654,67.2513,67.635025,68.4892
distance_km,50000.0,NaN,NaN,NaN,15.418266,8.339506,1.0,8.22,15.38,22.59,30.0
speed_kmh,50000.0,NaN,NaN,NaN,35.46503,13.788507,5.601448,24.845174,33.257728,44.924889,74.30668
traffic,50000,3,Low,18725,NaN,NaN,NaN,NaN,NaN,NaN,NaN
weather,50000,3,Clear,35010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vehicle_type,50000,3,Bus,16767,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timestamp,50000,29608,2025-01-26 21:28:00,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
day_of_week,50000.0,NaN,NaN,NaN,2.96988,1.951658,0.0,1.0,3.0,5.0,6.0
is_weekend,50000.0,NaN,NaN,NaN,0.2697,0.443808,0.0,0.0,0.0,1.0,1.0

## 5. Data Cleaning

Data cleaning is performed to identify and handle duplicate records, incorrect or inconsistent values, and columns that are not useful for machine learning.

The raw dataset is inspected before making any modifications so that the original data remains unchanged and the cleaning decisions can be justified.

In [12]:
# Check the total number of duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [14]:
# Display unique values for categorical/text columns

categorical_columns = df.select_dtypes(include=["str", "object"]).columns

for column in categorical_columns:
    print(f"\n{column}")
    print(df[column].unique())

user_id
<StringArray>
[  'U100',   'U101',   'U102',   'U103',   'U104',   'U105',   'U106',
   'U107',   'U108',   'U109',
 ...
 'U50090', 'U50091', 'U50092', 'U50093', 'U50094', 'U50095', 'U50096',
 'U50097', 'U50098', 'U50099']
Length: 50000, dtype: str

trip_id
<StringArray>
[ 'T9000',  'T9001',  'T9002',  'T9003',  'T9004',  'T9005',  'T9006',
  'T9007',  'T9008',  'T9009',
 ...
 'T58990', 'T58991', 'T58992', 'T58993', 'T58994', 'T58995', 'T58996',
 'T58997', 'T58998', 'T58999']
Length: 50000, dtype: str

traffic
<StringArray>
['Low', 'Medium', 'High']
Length: 3, dtype: str

weather
<StringArray>
['Clear', 'Fog', 'Rain']
Length: 3, dtype: str

vehicle_type
<StringArray>
['Bus', 'Car', 'Bike']
Length: 3, dtype: str

timestamp
<StringArray>
['2025-01-24 12:20:00', '2025-01-19 11:56:00', '2025-01-28 10:51:00',
 '2025-01-29 08:53:00', '2025-01-13 17:30:00', '2025-01-02 19:41:00',
 '2025-01-27 18:47:00', '2025-01-02 01:58:00', '2025-01-22 15:31:00',
 '2025-01-29 08:36:00',
 ...
 '2025-01-07 03:29:00', '2025-01-22 09:49:00', '2025-01-22 23:23:00',
 '2025-01-08 15:03:00', '2025-01-21 20:04:00', '2025-01-08 09:05:00',
 '2025-01-11 06:25:00', '2025-01-05 16:55:00', '2025-01-22 00:02:00',
 '2025-01-11 01:08:00']
Length: 29608, dtype: str

In [15]:
# Display minimum and maximum values of numerical columns

numerical_columns = df.select_dtypes(include="number").columns

for column in numerical_columns:
    print(
        f"{column}: "
        f"min = {df[column].min()}, "
        f"max = {df[column].max()}"
    )

start_lat: min = 24.0, max = 25.5
start_lon: min = 66.5001, max = 68.0
end_lat: min = 23.5038, max = 25.9948
end_lon: min = 66.004, max = 68.4892
distance_km: min = 1.0, max = 30.0
speed_kmh: min = 5.601448407946176, max = 74.30667989113918
day_of_week: min = 0, max = 6
is_weekend: min = 0, max = 1

In [16]:
# Display all columns in the dataset
print("Columns in the dataset:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Columns in the dataset:
1. user_id
2. trip_id
3. start_lat
4. start_lon
5. end_lat
6. end_lon
7. distance_km
8. speed_kmh
9. traffic
10. weather
11. vehicle_type
12. timestamp
13. day_of_week
14. is_weekend